### ISSUE TITLE
"Roll a die" - ValueError

### ISSUE THREAD

**Issue by krisgesling** [Dragoncraft89/dice-skill#5]
Hi Florian, 

I found that the dice skill sometimes fails if my "roll a dice" gets interpreted as "roll a die". [Line #22](https://github.com/Dragoncraft89/dice-skill/blob/7d2997a8fe57c13d56a2379ffc42ef1d08257c8d/__init__.py#L22) returns a
> ValueError: invalid literal for int() with base 10: 'ie'

Could add a check for integers before attempting the split?

Love the skill though!

**Comment by yvie-k** [comment]
This should be easy to fix.

Thanks for the report :+1:

**Comment by yvie-k** [comment]
Will upload the new version now
