### ISSUE TITLE
Allow multiple dice rolls

### ISSUE THREAD

**Issue by natrius** [Dragoncraft89/dice-skill#9]
Ex.

> Hey Mycroft, roll three dices

or 

> Hey Mycroft, roll two d20

Answer could be:

> The first number is 3, the second number is 6, the third number is 1

**Comment by yvie-k** [comment]
Hi natrius,
this should already be working. Maybe the voice recognition fails on this phrase? Can you provide the output generated by mycroft? (What phrase it recognizes and the response to that)

**Comment by natrius** [comment]
Hey, sorry for the late replay, i tried at least my first one again and it worked. Output was 

> Your numbers are: 3, 5

I will try the second one with the d20 again today. If it works i will close the issue.

**Comment by natrius** [comment]
*lol* now it does not work... Output 

![image](https://user-images.githubusercontent.com/7243447/77661379-da74c380-6f7a-11ea-9a49-bef3b4e03baf.png)

Ooooh, i think i got it now. The skill does not understand `dices`, just `dice`

At least the "two d20" works as well :D

**Comment by yvie-k** [comment]
Well, `dice` is already the plural form. The singular is `die`.

So this is strictly speaking not a bug. 😆 

Not sure whether to close this, or add the wrong plural form to the list of accepted words

**Comment by natrius** [comment]
Oh, whopps. That explains a lot. 

Nah, in my opinion its fine. Don't encourage me :D
